networks:
  ds517net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24

services:

  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    hostname: attacker
    networks:
      ds517net:
        ipv4_address: 172.29.0.10
    volumes:
      - ./attacker:/scripts
    tty: true
    stdin_open: true
    # Se instalan curl y python3 automáticamente para que los scripts de ataque funcionen
    command: /bin/bash -c "apt-get update -qq && apt-get install -y curl python3 >/dev/null 2>&1 && /bin/bash"

  siem:
    build: ./siem
    container_name: siem
    hostname: siem
    networks:
      ds517net:
        ipv4_address: 172.29.0.30
    ports:
      - "5601:5601"
    tty: true
    stdin_open: true

  victim:
    build: ./victim
    container_name: victim
    hostname: victim
    networks:
      ds517net:
        ipv4_address: 172.29.0.20
    depends_on:
      - siem
    tty: true
    stdin_open: true

  suniver:
    build: ./suniver
    container_name: suniver
    hostname: suniver
    networks:
      ds517net:
        ipv4_address: 172.29.0.50
    ports:
      - "7000:7000"
    tty: true
    stdin_open: true

  database:
    build: ./database
    container_name: database
    hostname: database
    networks:
      ds517net:
        ipv4_address: 172.29.0.60
    ports:
      - "5050:5050"
    depends_on:
      - siem
    tty: true
    stdin_open: true

  admin:
    build: ./admin
    container_name: admin
    hostname: admin
    networks:
      ds517net:
        ipv4_address: 172.29.0.40
    ports:
      - "8080:8080"
    depends_on:
      - siem
      - victim
      - database
    tty: true
    stdin_open: true